spring:
#  redis:
#    database: 0
#    host: 192.168.3.111
#    port: 6379
#    password:
#    lettuce:
#      pool:
#        # 连接池中的最大空闲连接 默认8
#        max-idle: 8
#        # 连接池中的最小空闲连接 默认0
#        min-idle: 0
#        # 连接池最大连接数 默认8 ，负数表示没有限制
#        max-active: 200
#        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
#        max-wait: -1
#    timeout: 30000
  datasource:
    druid:
      # 配置sqlite文件路径，需要填写绝对路径，推荐将sqlite文件放入到服务器上，而非程序jar包或war包中
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/COMMON?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: root
#      driver-class-name: dm.jdbc.driver.DmDriver
#      url: jdbc:dm://192.168.199.55:5236?schema=CROSSCHAIN_SYNC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
#      username: SYSDBA
#      password: SYSDBA001
      #使用Druid数据源
      initialSize: 5
      # 初始化大小，最小，最大
      minIdle: 20
      maxActive: 1000
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,slf4j
      filter:
        stat:
          merge-sql: false
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.slowSqlMillis=5000
file:
  path: D:/upload
  herf: /img/
  zip: z:/zip
